/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

import javax.swing.table.DefaultTableModel;
import model.Pedido;
import java.util.ArrayList;


/**
 *
 * @author pedro
 */
public class PainelPedidos extends javax.swing.JPanel {

    TelaPrincipal telaPrincipal;
    DefaultTableModel pedidoTableModel;
    ArrayList<Pedido> pedidos;

    /**
     * Creates new form PainelPedidos
     */
    public PainelPedidos(TelaPrincipal telaPrincipal) {
        initComponents();

        this.telaPrincipal = telaPrincipal;
        pedidoTableModel = (DefaultTableModel) jTable1.getModel();


        //Pedido pedido1 = new Pedido();
       // telaPrincipal.adicionarPedidoNaLista(pedido1);

        //this.pedidos = telaPrincipal.getPedidos();




//        for(Pedido pedido : telaPrincipal.getPedidos()) {
//
//            adicionarLinhaTabela(pedido);
//        }
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pedido", "Preço"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Novo Pedido");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Procurar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(51, 51, 51)
                .addComponent(jTextField1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FazerPedido telaFazerPedido = new FazerPedido(this.telaPrincipal);
        telaFazerPedido.setVisible(true);

        //telaPrincipal.adionarPedidoNaLista(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

//        Pedido pedido1 = new Pedido();
//        telaPrincipal.adicionarPedidoNaLista(pedido1);
//
//        this.pedidos = telaPrincipal.getPedidos();
//
//
//
//
//        for(Pedido pedido : telaPrincipal.getPedidos()) {
//
//            adicionarLinhaTabela(pedido);
//
//  }
        }//GEN-LAST:event_jButton2ActionPerformed


    private void adicionarLinhaTabela(Pedido pedido) {

        pedidoTableModel.addRow(new Object[]{String.valueOf(pedido.getNumPedido())});

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
