/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

import javax.swing.JComponent;
import model.Funcionario;

/**
 *
 * @author pedro
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    Funcionario funcionarioSessaoAtual;

    /**
     * Creates new form TelaAdministrador
     */
    public TelaPrincipal(Funcionario funcionario) {
        
        initComponents();
        
        this.funcionarioSessaoAtual = funcionario;
        
        JComponent painelEntregas = new PainelEntregas();
        JComponent painelCardapio = new PainelCardapio();
        JComponent painelPedidos = new PainelPedidos();
        JComponent painelProdutos = new PainelProdutos();
        this.tabbedPane.addTab("Cardapio", painelCardapio);
        this.tabbedPane.addTab("Pedidos", painelPedidos);
        this.tabbedPane.addTab("Produtos", painelProdutos);
        this.tabbedPane.addTab("Entregas", painelEntregas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables
}
