/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
package visual.painel;

import javax.swing.table.DefaultTableModel;
import model.pedido.Pedido;
import java.util.ArrayList;
import java.text.DecimalFormat;
import visual.tela.TelaFazerPedido;
import visual.tela.TelaPrincipal;


/**
 *
 * @author pedro
 */
public class PainelPedidos extends javax.swing.JPanel {
    
    private TelaPrincipal telaPrincipal;
    private DefaultTableModel pedidoTableModel;
    private ArrayList<Pedido> pedidos;
    private static final DecimalFormat df = new DecimalFormat("R$ #,##0.00");
    
    /**
     * Creates new form PainelPedidos
     */
    public PainelPedidos(TelaPrincipal telaPrincipal) {
        initComponents();
        this.telaPrincipal = telaPrincipal;
        pedidoTableModel = (DefaultTableModel) tabelaDePedidos.getModel();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaDePedidos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        tabelaDePedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pedido", "Cliente", "Total do pedido"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaDePedidos);

        jButton1.setText("Novo Pedido");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Procurar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(51, 51, 51)
                        .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        TelaFazerPedido telaFazerPedido = new TelaFazerPedido(this.telaPrincipal);
        telaFazerPedido.setVisible(true);
        
        //telaPrincipal.adionarPedidoNaLista(null);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        
        this.pedidos = telaPrincipal.getPedidos();
        
        for(int i = 0; i < pedidoTableModel.getRowCount(); i++) {
            
            pedidoTableModel.removeRow(i);
        }
        
        for(Pedido pedido : pedidos) {
            
            adicionarLinhaTabela(pedido);
            
            
            
        }
        }//GEN-LAST:event_jButton2ActionPerformed
    
    
    private void adicionarLinhaTabela(Pedido pedido) {
        pedidoTableModel.addRow(new Object[]{String.valueOf(pedido.getNumPedido()), df.format(pedido.getValorPedido())});
    }
    
    public void refresh() {
        DefaultTableModel modelEntrega = (DefaultTableModel) tabelaDePedidos.getModel();
        
        while(modelEntrega.getRowCount() > 0)
            modelEntrega.removeRow(0);
        
        for(Pedido pedido : telaPrincipal.getPedidos()) {
            
            String infoPedido = "Pedido nº " + pedido.getNumPedido();
            
            if(pedido.getCliente() != null)
                modelEntrega.addRow(new Object[]{infoPedido, pedido.getCliente().getNome(), TelaPrincipal.df.format(pedido.getValorPedido())});
            else
                modelEntrega.addRow(new Object[]{infoPedido, "desconhecido", TelaPrincipal.df.format(pedido.getValorPedido())});
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tabelaDePedidos;
    // End of variables declaration//GEN-END:variables
}
